version: '3.7'

services:
    frontend:
        build: 
            context: ./
            dockerfile: Dockerfile
        ports: 
            - 8080:8080
        volumes:
            - ./:/usr/src/ui